// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMeVf20rg0B4VGJUwFt2EHb52l58S25vo',
    appId: '1:672454909745:web:0031e88b94fdbed4de1a10',
    messagingSenderId: '672454909745',
    projectId: 'farmersapp-b799f',
    authDomain: 'farmersapp-b799f.firebaseapp.com',
    databaseURL: 'https://farmersapp-b799f-default-rtdb.firebaseio.com',
    storageBucket: 'farmersapp-b799f.firebasestorage.app',
    measurementId: 'G-99MYTBEJE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Sgxw3yjBA20r16nzZq0hWCkE-oAD8WA',
    appId: '1:672454909745:android:0d7c818ac26d8047de1a10',
    messagingSenderId: '672454909745',
    projectId: 'farmersapp-b799f',
    databaseURL: 'https://farmersapp-b799f-default-rtdb.firebaseio.com',
    storageBucket: 'farmersapp-b799f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk29JYoclnm5pqFENAy5Oi__dGPlcwC48',
    appId: '1:672454909745:ios:decf9034479188abde1a10',
    messagingSenderId: '672454909745',
    projectId: 'farmersapp-b799f',
    databaseURL: 'https://farmersapp-b799f-default-rtdb.firebaseio.com',
    storageBucket: 'farmersapp-b799f.firebasestorage.app',
    iosBundleId: 'com.example.farmapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk29JYoclnm5pqFENAy5Oi__dGPlcwC48',
    appId: '1:672454909745:ios:decf9034479188abde1a10',
    messagingSenderId: '672454909745',
    projectId: 'farmersapp-b799f',
    databaseURL: 'https://farmersapp-b799f-default-rtdb.firebaseio.com',
    storageBucket: 'farmersapp-b799f.firebasestorage.app',
    iosBundleId: 'com.example.farmapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMeVf20rg0B4VGJUwFt2EHb52l58S25vo',
    appId: '1:672454909745:web:50511822ff22d09dde1a10',
    messagingSenderId: '672454909745',
    projectId: 'farmersapp-b799f',
    authDomain: 'farmersapp-b799f.firebaseapp.com',
    databaseURL: 'https://farmersapp-b799f-default-rtdb.firebaseio.com',
    storageBucket: 'farmersapp-b799f.firebasestorage.app',
    measurementId: 'G-27GFY015ZE',
  );
}
